#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# Depends on sensio/framework-extra-bundle, doctrine/annotations, and doctrine/cache
#   install with composer req sensio/framework-extra-bundle annot
demo_controllers:
    resource: ../src/Demo/Application/Controller/
    type: annotation
