#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

core:
  # loads routes from the YAML or XML files found in some bundle directory
  resource: '../src/Core/Infrastructure/Resources/routing/'
  type:     directory
